import { templates } from "./n8n";
import {
  models,
  model_metrics,
  inferences,
  modelsRelations,
  model_metricsRelations,
  inferencesRelations,
} from "./model";
import {
  workflows,
  nodes,
  edges,
  workflowRunHistory,
  workflowsRelations,
  nodesRelations,
  edgesRelations,
} from "./workflow";
import { endpoints, endpointsRelations } from "./endpoint";
import { widgets, widgetsRelations } from "./widget";
import {
  rules,
  rule_flows,
  condition_groups,
  conditions,
  rule_flow_actions,
  rulesRelations,
  ruleFlowsRelations,
  conditionGroupsRelations,
  conditionsRelations,
  ruleFlowActionsRelations,
} from "./rule";
import {
  decision_tables,
  decision_table_rows,
  decision_table_inputs,
  decision_table_outputs,
  decision_table_input_conditions,
  decision_table_output_results,
  decisionTablesRelations,
  decisionTableRowsRelations,
  decisionTableInputsRelations,
  decisionTableOutputsRelations,
  decisionTableInputConditionsRelations,
  decisionTableOutputResultsRelations,
} from "./decision_table";
import {
  knowledge_bases,
  knowledge_base_documents,
  conversations,
  conversation_messages,
  knowledgeBaseRelations,
  knowledgeBaseDocumentRelations,
  knowledgeBaseConversationRelations,
  conversationRelations,
  conversationMessageRelations,
} from "./knowledge_base";

export {
  templates,
  models,
  model_metrics,
  inferences,
  workflows,
  nodes,
  edges,
  workflowRunHistory,
  nodesRelations,
  edgesRelations,
  endpoints,
  widgets,
  workflowsRelations,
  endpointsRelations,
  widgetsRelations,
  rules,
  rule_flows,
  condition_groups,
  conditions,
  rule_flow_actions,
  rulesRelations,
  ruleFlowsRelations,
  conditionGroupsRelations,
  conditionsRelations,
  ruleFlowActionsRelations,
  modelsRelations,
  model_metricsRelations,
  inferencesRelations,
  decision_tables,
  decision_table_rows,
  decision_table_inputs,
  decision_table_outputs,
  decision_table_input_conditions,
  decision_table_output_results,
  decisionTablesRelations,
  decisionTableRowsRelations,
  decisionTableInputsRelations,
  decisionTableOutputsRelations,
  decisionTableInputConditionsRelations,
  decisionTableOutputResultsRelations,
  knowledge_bases,
  knowledge_base_documents,
  conversations,
  conversation_messages,
  knowledgeBaseRelations,
  knowledgeBaseDocumentRelations,
  knowledgeBaseConversationRelations,
  conversationRelations,
  conversationMessageRelations,
};

export default {
  templates,
  workflows,
  endpoints,
  widgets,
  nodes,
  edges,
  workflowRunHistory,
  nodesRelations,
  edgesRelations,
  workflowsRelations,
  endpointsRelations,
  widgetsRelations,
  rules,
  rule_flows,
  condition_groups,
  conditions,
  rule_flow_actions,
  rulesRelations,
  ruleFlowsRelations,
  conditionGroupsRelations,
  conditionsRelations,
  ruleFlowActionsRelations,
  models,
  model_metrics,
  inferences,
  modelsRelations,
  model_metricsRelations,
  inferencesRelations,
  decision_tables,
  decision_table_rows,
  decision_table_inputs,
  decision_table_outputs,
  decision_table_input_conditions,
  decision_table_output_results,
  decisionTableInputConditionsRelations,
  decisionTableOutputResultsRelations,
  decisionTablesRelations,
  decisionTableRowsRelations,
  decisionTableInputsRelations,
  decisionTableOutputsRelations,
  knowledge_bases,
  knowledge_base_documents,
  knowledgeBaseRelations,
  knowledgeBaseDocumentRelations,
  conversations,
  conversation_messages,
  knowledgeBaseConversationRelations,
  conversationRelations,
  conversationMessageRelations,
};
