ALTER TABLE "lookup_table_cells" ALTER COLUMN "id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "lookup_table_cells" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "lookup_table_cells_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "lookup_table_dimension_bins" ALTER COLUMN "id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "lookup_table_dimension_bins" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "lookup_table_dimension_bins_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "lookup_tables" ALTER COLUMN "id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "lookup_tables" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "lookup_tables_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "lookup_table_inputs" ALTER COLUMN "id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "lookup_table_inputs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "lookup_table_inputs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "lookup_table_outputs" ALTER COLUMN "id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "lookup_table_outputs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "lookup_table_outputs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);